name: distech_technology
description: Online Lottery Management Application
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.5+17

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.1.0
  dio: ^5.1.2
  equatable: ^2.0.5
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  otp_text_field: ^1.1.3
  get: ^4.6.5
  flutter_barcode_scanner:
  pull_to_refresh: ^2.0.0
  upgrader: ^8.1.0
  # flutter_screenutil: ^5.9.0
  zefyr: any
  crypto: ^3.0.3
  base32: any
  awesome_dialog: 
  #svg pic
  flutter_svg: ^2.0.9
  #user agent
  flutter_user_agentx: ^1.2.4
  horizontal_data_table: ^4.3.1

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/launcherIcons/icon.png"
  android: true
  ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/launcherIcons/icon.png"
    background_color: "#1F6AFD"
    theme_color: "#1F6AFD"
  windows:
    generate: true
    image_path: "assets/launcherIcons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/launcherIcons/icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
